config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  resources :users do
    get 'shows/behind', to: 'shows#behind'
    resources :shows, only: [:index]
  end
  
  resources :shows do
    
  end
  resources :genres, only: [:index, :show]
  resources :channels, only: [:index, :show]
  get '/search', to: 'shows#search'
  get '/auth/google/callback', to: 'users#google_login'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  
  resources :favorite_shows, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/channel.rb
class Channel < ApplicationRecord
  has_many :shows
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :favorited, polymorphic: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :show_genres
  has_many :shows, through: :show_genres
end

app/models/show.rb
class Show < ApplicationRecord
  has_many :listings
  has_many :watchlists, through: :listings
  has_many :users, through: :listings
  has_many :show_genres
  has_many :genres, through: :show_genres
  has_many :favorites, dependent: :destroy
  belongs_to :channel

  validates :title, presence: true, uniqueness: { scope: :channel_id } # Validates uniqueness of title and channel
  validates :current_season, presence: true, numericality: { greater_than: 0 }

  scope :search, -> (query) { joins(:channel).where("lower(title) LIKE ? OR lower(channels.name) LIKE ?", "%" + query.downcase + "%", "%" + query.downcase + "%") }
  scope :behind_on, -> (user_id) { joins(:listings).where('shows.current_season > listings.user_season').where(listings: {user_id: user_id}).uniq }

  def channel_attributes=(channel_attributes)
    channel_attributes.values.each do |channel_attribute|
      unless channel_attribute.blank?
        channel = Channel.find_or_create_by(name: channel_attribute)
        self.channel = channel
      end
    end
  end

  def genres_attributes=(genre_attributes)
    genre_name = genre_attributes["0"]["name"]
    unless genre_name.blank?
      genre = Genre.find_or_create_by(name: genre_name)
      self.genres << genre
    end
  end

  def shows_watchlists_by_user(user_id)
    self.listings.where(user_id: user_id)
  end
  
end

app/models/show_genre.rb
class ShowGenre < ApplicationRecord
  belongs_to :show
  belongs_to :genre
end

app/models/user.rb
class User < ApplicationRecord
  

  has_many :watchlists
  has_many :favorites
  has_many :favorite_shows, through: :favorites, source: :favorited, source_type: 'Show'
  has_many :shows, through: :favorites, source: :favorited, source_type: 'Show'

  validates :email, presence: true, uniqueness: true
  validates :username, presence: true

  has_secure_password

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
  def current_user
    @user = User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end

  def require_login
    unless logged_in?
      flash[:danger] = "You must be logged in to access this section!"
      redirect_to login_path
    end
  end
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  
end

app/controllers/favorite_shows_controller.rb
class FavoriteShowsController < ApplicationController
    before_action :set_show
    
    def create
      if Favorite.create(favorited: @show, user: current_user)
        redirect_to shows_path, notice: 'Show has been favorited...!'
      end
    end
    
    def destroy
      Favorite.where(favorited_id: @show.id, user_id: current_user.id).first.destroy
      redirect_to shows_path, notice: 'Show has been removed from favorites...!'
    end
    
    private
    
    def set_show
      @show = Show.find(params[:show_id] || params[:id])
    end
  end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :require_login

  def index
    @genres = Genre.all
  end

  def show
    @genre = Genre.find_by(id: params[:id])
    @shows = @genre.shows
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  helper_method :logged_in?, :current_user
  layout "static"

  def new
    if logged_in?
      redirect_to shows_path(current_user)
    end
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to shows_path(user)
    else
      flash[:danger] = "Wrong email and/or password"
      render :new
    end
  end

  def destroy
    if logged_in?
      session.clear
      redirect_to '/'
    else
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  before_action :require_login
  before_action :set_show, only: [:show, :edit, :update]
  before_action :created_by_current_user, only: [:edit, :update]
  helper_method :current_user

  def index
    @user = User.find_by(id: params[:user_id])
    if @user
      @shows = @user.shows.uniq
    else
      @shows = Show.all
    end
  end

  def show
  end

  def new
    @show = Show.new
   
  end

  def create
    @show = Show.new(show_params)
    if @show.save
      flash[:message] = "#{@show.title} has been created"
      redirect_to show_path(@show)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @show.update(show_params)
    if @show.save
      flash[:message] = "#{@show.title} has been updated"
      redirect_to show_path(@show)
    else
      render :edit
    end
  end

  def search
    @shows = Show.search(params[:query])
    render :index
  end

  def behind
    @shows = Show.behind_on(params[:user_id])
    render :index
  end

  private
  def show_params
    params.require(:show).permit( :title, :description, :channel_id, :day, :current_season, :created_by, genre_ids:[], genres_attributes:[:name], channel_attributes:[:name])
  end

  def set_show
    @show = Show.find_by(id: params[:id])
  end

  def created_by_current_user
    unless @show.created_by == current_user.id
      flash[:danger] = "You cannot edit this show because you did not create it!"
      redirect_to show_path(@show)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  helper_method :logged_in?, :current_user
  layout "static"

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to shows_path(@user)
    else
      render :new
    end
  end

  def show
    @user = current_user
    if logged_in?
      if @user == User.find_by(id: params[:id])
        render :layout => "application"
      else
        flash[:danger] = "You don't have access to view that user's settings!"
        redirect_to shows_path(@user)
      end
    else
      redirect_to login_path
    end
  end

  
  private
  def user_params
    params.require(:user).permit(:email, :username, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def alphebetize(collection)
    case when collection.first.class == Show
      collection.sort_by { |s| s.title }
    else
      collection.sort_by { |s| s.name }
    end
  end
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
  def watchlist_options(listings, show)
    if @listings.count > 0
      render :partial => "listings/details", :locals => {:listings => listings, :show => show}
    else
      "None"
    end
  end
end

app/views/channels/index.html.erb
<% content_for :content do %>
<% end %>

app/views/channels/show.html.erb
<% content_for :content do %>
<% end %>

app/views/genres/index.html.erb
<% content_for :content do %>
<% end %>

app/views/genres/show.html.erb
<% content_for :content do %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChannelApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-primary global-notification">
        <p class="notice"><%= notice %></p>     
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="notification is-danger global-notification">
        <p class="alert"><%= alert %></p>     
      </div>
    <% end %>
    <nav class=" navbar is-info">
      <div class="navbar-brand">
        <%= link_to root_path, class: "navbar-item" do %>
          <h1 class="title is-5">ChannelApp</h1>
        <% end %>
        <div class="navbar-burger burger" data-taget="navbarExample">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>

      <div id="navbarExample" class="navbar-menu">
        <div class="navbar-end">
          <div class="field is-grouped">
            <p class="control">
              <% if current_user %>
                <%= link_to(current_user.username, edit_user_path(current_user), class: "button is-info") %>  
              <% end %>
            </p>
            <p class="control">
              <% if current_user %>
              
              <%= link_to('Logout', logout_path, class: "button is-info") %>        
              
            <% else %>
              
              <%= link_to('Login', login_path, class: "button is-info") %>  
              
            <% end %>
            </p>
          </div>
        </div>
      </div>
    </nav>
    <section class="section">
      <div class="container">
        <div class="columns">
          <div class="column">
            <nav class="panel">
              <p class="panel-heading">Profile</p>
              <div class="panel-block">
                <article class="media">
                  <div class="media-left">
                    <figure class="image is64x64">
                      <%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.username) %>
                    </figure>
                  </div>
                  <div class="media-content">
                    <div class="content">
                      <p>
                        <strong><%= current_user.username %></strong>
                      </p>
                    </div>
                  </div>
                </article>
              </div>
              <div class="panel-block">
                <div class="level is-mobile">
                  <div class="level-item has-centered-text">
                    <div>
                      <p class="heading"><h1><%= link_to "Browse Shows", shows_path %></h1></p>
                    </div>
                  </div>
                </div>
              </div>
              <div class="panel-block">
                <div class="level is-mobile">
                  <div class="level-item has-centered-text">
                    <div>
                      <p class="heading"><h1><%= link_to "Add New Show", new_show_path, :method => "get", class: "btn btn-info btn-block" %></h1></p>
                    </div>
                  </div>
                </div>
              </div>
            </nav>
          </div>
          <%= yield :content %>
          <div class="column">
            <nav class="panel">
              <p class="panel-heading">
                Advertisement
              </p>
            </nav>
          
            <div class="panel-block">
              <article class="media">
                <div class="media-left">
                  
                </div>
                <div class="media-content">
                  <div class="content">
                    <p>
                      
                    </p>
                  </div>
                </div>
              </article>
            </div>
          </div>
        </div>    
      </div>
    </section>
    <%= yield %>
  </body>
</html>

app/views/layouts/static.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FavShowApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="m-3">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shows/_form.html.erb
<div class="column is-half ">
  <article class="media box">
    <div class="media-content">
      <% if @show.errors.any? %>
        <div class="alert alert-danger" role="alert">
          <ul>
            <% @show.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <%= form_for(show) do |f| %>
        <div class="field">
          <%= f.label :title, class: "label" %>
          <div class="control">            
            <%= f.text_field :title, class: "input", placeholder: "Enter Title" %><br>            
          </div>
        </div>

        <div class="field">
          <%= f.label :channel, class: "label" %>
          <div class="control">
            <%= f.collection_select :channel_id, alphebetize(Channel.all), :id, :name, {:include_blank => true}, {class: "input"} %>
          </div>
        </div>

        <div class="field">
          <%= f.label :current_season, class: "label" %>
          <div class="control">            
            <%= f.number_field :current_season, class: "input", placeholder: "Enter Title" %><br>            
          </div>
        </div>


        <div class="field">
          <div class="control">
            <%= f.label :genre, class: "checkbox" %>
            <%= f.collection_check_boxes(:genre_ids, alphebetize(Genre.all), :id, :name) do |b| %>
              <div class="form-check form-check-inline">
                <%= b.check_box(class: "checkbox") %>
                <%= b.object.name %>
              </div>
            <% end %>
          </div>
        </div>

        <div class="field">
          <%= f.label :day, class: "label" %>
          <div class="control">            
            <%= f.text_field :day, class: "input", id: "datetimepicker",placeholder: "Enter Day" %>
          </div>
        </div>

        <%= f.hidden_field :created_by, value: current_user.id %>

        <div class="field">
          <%= f.label "Description", class: "label" %>
          <div class="control">
            <%= f.text_area :description, class:"textarea", placeholder: "Enter Discription" %><br>
          </div>
        </div>

        <div class="field is-grouped">
          <div class="control">
            <%= f.submit class: "button is-link" %>
          </div>
          <div class="control">
            <%= link_to "Cancel", shows_path, class: "button is-link is-light" %>
          </div>
        </div>
      <% end %>
    </div>
  </article>
</div>
<script>
  $('#datetimepicker').datetimepicker();
</script>

app/views/shows/_shows.html.erb
<table class="table table-striped table-hover table-light">
  <thead>
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Channel</th>
      <th scope="col">Day</th>
      <th scope="col">Time</th>
    </tr>
  </thead>
  <tbody>
    <% alphebetize(shows).each do |show| %>
      <tr>
        <th scope="row"><%= link_to show.title, show_path(show) %></th>
        <td><%= show.channel.name %></td>
        <td><%= show.day %></td>
        <td><%= show.time %></td>
        <!--<td><%= show.current_season %></td>
        <td><%= show.genres.map { |genre| genre.name }.join(', ') %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

app/views/shows/edit.html.erb
<% content_for :content do %>
  <%= render partial: "form", locals: {show: @show} %>
<% end %>

app/views/shows/index.html.erb
<% content_for :content do %>  
  <div class="column is-half ">
    <article class="media box">
      <div class="media-content">
        <%= form_tag("/search", method: "get") do %>
          <div class="field has-addons">
            <div class="control">
              <%= text_field_tag :query, "", class: "input", placeholder: "Find a Show" %>
            </div>
            <div class="control">
              <%= submit_tag "Search", class: "button is-info" %>
            </div>
          </div>
        <% end %>
      </div>
    </article>


    <% alphebetize(@shows).each do |show| %>
      <div class="box">
        <article class="media">
          <div class="media-left">
            <figure class="image is-64x64">
              <%= gravatar_image_tag(show.title, size: 64) %>
            </figure>
          </div>
          <div class="media-content">
            <div class="content">
              <strong><%= link_to show.title, show_path(show) %></strong>
              <small><%= show.channel.name %></small>
              <p><small><%= show.description %></small></p>
              <p><%= show.day.to_datetime.strftime("%a %d.%m.%Y") %> - <%= show.day.to_datetime.strftime("%I:%M %p") %> </p>
            </div>
          </div>
          <nav class="level">
            <div class="level-left is-mobile">
              <% unless current_user.favorite_shows.exists?(id: show.id) %>
                <%= link_to favorite_shows_path(show_id: show.id), method: :post, class: "level-item" do %>
                <!-- <span class="icon"><i class="fa fa-link" aria-hidden="true">Add to Faviriot</i></span> -->
                  <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-hand-thumbs-up" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M6.956 1.745C7.021.81 7.908.087 8.864.325l.261.066c.463.116.874.456 1.012.965.22.816.533 2.511.062 4.51a9.84 9.84 0 0 1 .443-.051c.713-.065 1.669-.072 2.516.21.518.173.994.681 1.2 1.273.184.532.16 1.162-.234 1.733.058.119.103.242.138.363.077.27.113.567.113.856 0 .289-.036.586-.113.856-.039.135-.09.273-.16.404.169.387.107.819-.003 1.148a3.163 3.163 0 0 1-.488.901c.054.152.076.312.076.465 0 .305-.089.625-.253.912C13.1 15.522 12.437 16 11.5 16v-1c.563 0 .901-.272 1.066-.56a.865.865 0 0 0 .121-.416c0-.12-.035-.165-.04-.17l-.354-.354.353-.354c.202-.201.407-.511.505-.804.104-.312.043-.441-.005-.488l-.353-.354.353-.354c.043-.042.105-.14.154-.315.048-.167.075-.37.075-.581 0-.211-.027-.414-.075-.581-.05-.174-.111-.273-.154-.315L12.793 9l.353-.354c.353-.352.373-.713.267-1.02-.122-.35-.396-.593-.571-.652-.653-.217-1.447-.224-2.11-.164a8.907 8.907 0 0 0-1.094.171l-.014.003-.003.001a.5.5 0 0 1-.595-.643 8.34 8.34 0 0 0 .145-4.726c-.03-.111-.128-.215-.288-.255l-.262-.065c-.306-.077-.642.156-.667.518-.075 1.082-.239 2.15-.482 2.85-.174.502-.603 1.268-1.238 1.977-.637.712-1.519 1.41-2.614 1.708-.394.108-.62.396-.62.65v4.002c0 .26.22.515.553.55 1.293.137 1.936.53 2.491.868l.04.025c.27.164.495.296.776.393.277.095.63.163 1.14.163h3.5v1H8c-.605 0-1.07-.081-1.466-.218a4.82 4.82 0 0 1-.97-.484l-.048-.03c-.504-.307-.999-.609-2.068-.722C2.682 14.464 2 13.846 2 13V9c0-.85.685-1.432 1.357-1.615.849-.232 1.574-.787 2.132-1.41.56-.627.914-1.28 1.039-1.639.199-.575.356-1.539.428-2.59z"/>
                  </svg>
                <% end %>
              <% else %>
                <%= link_to favorite_show_path(show), method: :delete do %>
                  <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-hand-thumbs-down" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M6.956 14.534c.065.936.952 1.659 1.908 1.42l.261-.065a1.378 1.378 0 0 0 1.012-.965c.22-.816.533-2.512.062-4.51.136.02.285.037.443.051.713.065 1.669.071 2.516-.211.518-.173.994-.68 1.2-1.272a1.896 1.896 0 0 0-.234-1.734c.058-.118.103-.242.138-.362.077-.27.113-.568.113-.857 0-.288-.036-.585-.113-.856a2.094 2.094 0 0 0-.16-.403c.169-.387.107-.82-.003-1.149a3.162 3.162 0 0 0-.488-.9c.054-.153.076-.313.076-.465a1.86 1.86 0 0 0-.253-.912C13.1.757 12.437.28 11.5.28v1c.563 0 .901.272 1.066.56.086.15.121.3.121.416 0 .12-.035.165-.04.17l-.354.353.353.354c.202.202.407.512.505.805.104.312.043.44-.005.488l-.353.353.353.354c.043.043.105.141.154.315.048.167.075.37.075.581 0 .212-.027.415-.075.582-.05.174-.111.272-.154.315l-.353.353.353.354c.353.352.373.714.267 1.021-.122.35-.396.593-.571.651-.653.218-1.447.224-2.11.164a8.907 8.907 0 0 1-1.094-.17l-.014-.004H9.62a.5.5 0 0 0-.595.643 8.34 8.34 0 0 1 .145 4.725c-.03.112-.128.215-.288.255l-.262.066c-.306.076-.642-.156-.667-.519-.075-1.081-.239-2.15-.482-2.85-.174-.502-.603-1.267-1.238-1.977C5.597 8.926 4.715 8.23 3.62 7.93 3.226 7.823 3 7.534 3 7.28V3.279c0-.26.22-.515.553-.55 1.293-.138 1.936-.53 2.491-.869l.04-.024c.27-.165.495-.296.776-.393.277-.096.63-.163 1.14-.163h3.5v-1H8c-.605 0-1.07.08-1.466.217a4.823 4.823 0 0 0-.97.485l-.048.029c-.504.308-.999.61-2.068.723C2.682 1.815 2 2.434 2 3.279v4c0 .851.685 1.433 1.357 1.616.849.232 1.574.787 2.132 1.41.56.626.914 1.28 1.039 1.638.199.575.356 1.54.428 2.591z"/>
                  </svg>
                <% end %>
              <% end %>
            </div>
          </nav>
        </article>
      </div>
    <% end %>
  </div>
<% end %>

app/views/shows/new.html.erb
<% content_for :content do %>
  <%= render partial: "form", locals: {show: @show} %>
<% end %>

app/views/shows/show.html.erb
<% content_for :content do %>
  <div class="column is-half ">
    <article class="media box">
      <div class="media-content">

        <h1><%= @show.title %></h1>

  
  <p><strong>Description</strong>: <%= @show.description %></p>
  <p><strong>Channel</strong>: <%= link_to @show.channel.name, channel_path(@show.channel) %></p>
  <p><strong>Current Season</strong>: <%= @show.current_season %></p>
  <p><strong>Genres</strong>: <%= @show.genres.map { |genre| link_to(genre.name, genre_path(genre)) }.join(', ').html_safe %></p>
  <p><strong>Day</strong>: <%= @show.day %></p>
  <p><strong>Time</strong>: <%= @show.time %></p>
  <p><% unless current_user.favorite_shows.exists?(id: @show.id) %>
  
  <%= link_to favorite_shows_path(show_id: @show.id), method: :post, class: "level-item" do %>Add to favorites
                <!-- <span class="icon"><i class="fa fa-link" aria-hidden="true">Add to Faviriot</i></span> -->
                  <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-hand-thumbs-up" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M6.956 1.745C7.021.81 7.908.087 8.864.325l.261.066c.463.116.874.456 1.012.965.22.816.533 2.511.062 4.51a9.84 9.84 0 0 1 .443-.051c.713-.065 1.669-.072 2.516.21.518.173.994.681 1.2 1.273.184.532.16 1.162-.234 1.733.058.119.103.242.138.363.077.27.113.567.113.856 0 .289-.036.586-.113.856-.039.135-.09.273-.16.404.169.387.107.819-.003 1.148a3.163 3.163 0 0 1-.488.901c.054.152.076.312.076.465 0 .305-.089.625-.253.912C13.1 15.522 12.437 16 11.5 16v-1c.563 0 .901-.272 1.066-.56a.865.865 0 0 0 .121-.416c0-.12-.035-.165-.04-.17l-.354-.354.353-.354c.202-.201.407-.511.505-.804.104-.312.043-.441-.005-.488l-.353-.354.353-.354c.043-.042.105-.14.154-.315.048-.167.075-.37.075-.581 0-.211-.027-.414-.075-.581-.05-.174-.111-.273-.154-.315L12.793 9l.353-.354c.353-.352.373-.713.267-1.02-.122-.35-.396-.593-.571-.652-.653-.217-1.447-.224-2.11-.164a8.907 8.907 0 0 0-1.094.171l-.014.003-.003.001a.5.5 0 0 1-.595-.643 8.34 8.34 0 0 0 .145-4.726c-.03-.111-.128-.215-.288-.255l-.262-.065c-.306-.077-.642.156-.667.518-.075 1.082-.239 2.15-.482 2.85-.174.502-.603 1.268-1.238 1.977-.637.712-1.519 1.41-2.614 1.708-.394.108-.62.396-.62.65v4.002c0 .26.22.515.553.55 1.293.137 1.936.53 2.491.868l.04.025c.27.164.495.296.776.393.277.095.63.163 1.14.163h3.5v1H8c-.605 0-1.07-.081-1.466-.218a4.82 4.82 0 0 1-.97-.484l-.048-.03c-.504-.307-.999-.609-2.068-.722C2.682 14.464 2 13.846 2 13V9c0-.85.685-1.432 1.357-1.615.849-.232 1.574-.787 2.132-1.41.56-.627.914-1.28 1.039-1.639.199-.575.356-1.539.428-2.59z"/>
                  </svg>
                <% end %>
  <% else %>
  <%= link_to favorite_show_path(@show), method: :delete, class: "level-item" do %>Remove from favorites
                  <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-hand-thumbs-down" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M6.956 14.534c.065.936.952 1.659 1.908 1.42l.261-.065a1.378 1.378 0 0 0 1.012-.965c.22-.816.533-2.512.062-4.51.136.02.285.037.443.051.713.065 1.669.071 2.516-.211.518-.173.994-.68 1.2-1.272a1.896 1.896 0 0 0-.234-1.734c.058-.118.103-.242.138-.362.077-.27.113-.568.113-.857 0-.288-.036-.585-.113-.856a2.094 2.094 0 0 0-.16-.403c.169-.387.107-.82-.003-1.149a3.162 3.162 0 0 0-.488-.9c.054-.153.076-.313.076-.465a1.86 1.86 0 0 0-.253-.912C13.1.757 12.437.28 11.5.28v1c.563 0 .901.272 1.066.56.086.15.121.3.121.416 0 .12-.035.165-.04.17l-.354.353.353.354c.202.202.407.512.505.805.104.312.043.44-.005.488l-.353.353.353.354c.043.043.105.141.154.315.048.167.075.37.075.581 0 .212-.027.415-.075.582-.05.174-.111.272-.154.315l-.353.353.353.354c.353.352.373.714.267 1.021-.122.35-.396.593-.571.651-.653.218-1.447.224-2.11.164a8.907 8.907 0 0 1-1.094-.17l-.014-.004H9.62a.5.5 0 0 0-.595.643 8.34 8.34 0 0 1 .145 4.725c-.03.112-.128.215-.288.255l-.262.066c-.306.076-.642-.156-.667-.519-.075-1.081-.239-2.15-.482-2.85-.174-.502-.603-1.267-1.238-1.977C5.597 8.926 4.715 8.23 3.62 7.93 3.226 7.823 3 7.534 3 7.28V3.279c0-.26.22-.515.553-.55 1.293-.138 1.936-.53 2.491-.869l.04-.024c.27-.165.495-.296.776-.393.277-.096.63-.163 1.14-.163h3.5v-1H8c-.605 0-1.07.08-1.466.217a4.823 4.823 0 0 0-.97.485l-.048.029c-.504.308-.999.61-2.068.723C2.682 1.815 2 2.434 2 3.279v4c0 .851.685 1.433 1.357 1.616.849.232 1.574.787 2.132 1.41.56.626.914 1.28 1.039 1.638.199.575.356 1.54.428 2.591z"/>
                  </svg>
                <% end %>
  <% end %>
  </p>



      </div>
    </article>
  </div>  
<% end %>

app/views/users/show.html.erb
<% content_for :header do %>
  <h1>Account Settings</h1>
<% end %>

<% content_for :vertical_nav do %>
  <ul class="nav flex-column">
    
  </ul>
<% end %>

<% content_for :content do %>
  <strong>Email:</strong> <%= @user.email %><br>
  <strong>Name:</strong> <%= @user.username %><br>
<% end %>

<% content_for :sidebar do %>
  <%= button_to "Logout", logout_path, :method => "get", class: "btn btn-danger btn-block" %>
<% end %>